services:
  # nginx server container
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:rw
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./staticfiles:/staticfiles:ro  
    depends_on:
      - awm_django_app
    networks:
      - app_network

  # django app container
  awm_django_app:
    image: geodjango_tutorial
    build: .
    environment:
      - DJANGO_ALLOWED_HOSTS=jiaqianzhang.site,www.jiaqianzhang.site,localhost,127.0.0.1,[::1],awm_django_app,geodjango_tutorial-awm_django_app-1
      - GDAL_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/libgdal.so
      - GEOS_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/libgeos_c.so
      - GDAL_DATA=/usr/share/gdal
      - PROJ_LIB=/usr/share/proj
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_HOST=postgis
      - DJANGO_DEBUG=1
      - PYTHONUNBUFFERED=1
      - DJANGO_LOG_LEVEL=DEBUG
    volumes:
      - .:/app
      - ./staticfiles:/staticfiles  
    ports:
      - "8001:8001"
    depends_on:
      - postgis
    entrypoint: []  # Clear any existing entrypoint
    command: >
      /bin/bash -c "
        cd /app &&
        . /opt/conda/etc/profile.d/conda.sh &&
        conda activate env &&
        exec python -u manage.py runserver 0.0.0.0:8001
      "
    networks:
      - app_network

  # postgis container
  postgis:
    image: postgis/postgis
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  # pgadmin docker container
  pgadmin4:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=docker@example.com
      - PGADMIN_DEFAULT_PASSWORD=docker
    ports:
      - "20080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgis
    networks:
      - app_network

  # ssl cert update
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - app_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  app_network:
    driver: bridge
