services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:rw  # Changed to rw
      - ./certbot/www:/var/www/certbot:rw    # Changed to rw
      - ./certbot/conf:/etc/letsencrypt:rw   # Changed to rw
    user: root
    depends_on:
      - awm_django_app
    networks:
      - geodjango_tutorial

  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - "20080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: docker@example.com
      PGADMIN_DEFAULT_PASSWORD: docker
    volumes:
      - my_pgadmin4_data:/var/lib/pgadmin4
    depends_on:
      - postgis
    networks:
      - geodjango_tutorial

  postgis:
    image: postgis/postgis
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d gis"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - geodjango_tutorial

  awm_django_app:
    image: geodjango_tutorial
    build: .
    environment:
      - GDAL_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/libgdal.so
      - GEOS_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/libgeos_c.so
      - GDAL_DATA=/usr/share/gdal
      - PROJ_LIB=/usr/share/proj
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_HOST=postgis
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      postgis:
        condition: service_healthy
    command: >
      sh -c "
        conda run -n env python manage.py migrate &&
        conda run -n env python manage.py runserver 0.0.0.0:8001
      "
    networks:
      - geodjango_tutorial


  
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
    command: renew --noninteractive --webroot --webroot-path=/var/www/certbot
    depends_on:
      - nginx
    networks:
      - geodjango_tutorial


volumes:
  my_pgadmin4_data: {}
  postgres_data: {}

networks:
  geodjango_tutorial:
    driver: bridge  # Optional, but can specify bridge network

