services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:rw  # Changed to rw
      - ./certbot/www:/var/www/certbot:rw    # Changed to rw
      - ./certbot/conf:/etc/letsencrypt:rw   # Changed to rw
    user: root
    depends_on:
      - awm_django_app
    networks:
      - geodjango_tutorial

  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - "20080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: docker@example.com
      PGADMIN_DEFAULT_PASSWORD: docker
    volumes:
      - my_pgadmin4_data:/var/lib/pgadmin4
    depends_on:
      - postgis
    networks:
      - geodjango_tutorial

  postgis:
    image: kartoza/postgis
    ports:
      - "25432:5432"
    environment: 
      - POSTGRES_DB=postgis
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_HOST_AUTH_METHOD=md5
      - ALLOW_IP_RANGE=0.0.0.0/0
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-config/pg_hba.conf:/etc/postgresql/17/main/pg_hba.conf
    networks:
      - geodjango_tutorial
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d postgis"]
      interval: 10s
      timeout: 5s
      retries: 5


  awm_django_app:
    image: geodjango_tutorial
    build: .
    environment:
      - PROJ_LIB=/opt/conda/envs/env/share/proj
      - DJANGO_SETTINGS_MODULE=geodjango_tutorial.settings
      - PYTHONUNBUFFERED=1
      - POSTGRES_DB=postgis
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_HOST=postgis  # This will override the localhost default
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - postgis
    command: >
      sh -c "
        echo 'Waiting for PostgreSQL...' &&
        while ! nc -z postgis 5432; do
          sleep 1
          echo 'Still waiting for PostgreSQL...'
        done &&
        echo 'PostgreSQL is up!' &&
        conda run -n env python manage.py migrate &&
        conda run -n env python manage.py runserver 0.0.0.0:8001
      "
    networks:
      - geodjango_tutorial

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
    command: renew --noninteractive --webroot --webroot-path=/var/www/certbot
    depends_on:
      - nginx
    networks:
      - geodjango_tutorial
volumes:
  my_pgadmin4_data: {}
  my_first_spatialdb_data: {}
  postgres_data: {}

networks:
  geodjango_tutorial:
