services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:rw
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
    user: root
    depends_on:
      - awm_django_app
    networks:
      - geodjango_tutorial

  awm_django_app:
    image: geodjango_tutorial
    build: .
    environment:
      - GDAL_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/libgdal.so
      - GEOS_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/libgeos_c.so
      - GDAL_DATA=/usr/share/gdal
      - PROJ_LIB=/usr/share/proj
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_HOST=postgis
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_DEBUG=1
      - PYTHONUNBUFFERED=1
      - DJANGO_LOG_LEVEL=DEBUG
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - postgis
    entrypoint: []  # Clear any existing entrypoint
    command: >
      /bin/bash -c "
        cd /app &&
        . /opt/conda/etc/profile.d/conda.sh &&
        conda activate env &&
        exec python -u manage.py runserver 0.0.0.0:8001
      "
    networks:
      - geodjango_tutorial


  postgis:
    image: postgis/postgis
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - geodjango_tutorial

  pgadmin4:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=docker@example.com
      - PGADMIN_DEFAULT_PASSWORD=docker
    ports:
      - "20080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgis
    networks:
      - geodjango_tutorial

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
    depends_on:
      - nginx
    command: >
      certonly --webroot 
      --webroot-path=/var/www/certbot 
      --email c21408862@mytudublin.com  # Replace with your actual email
      --agree-tos 
      --no-eff-email 
      --staging
      --non-interactive
    networks:
      - geodjango_tutorial



volumes:
  postgres_data:
  pgadmin_data:

networks:
  geodjango_tutorial:
    driver: bridge
