# Generated by Django 5.1 on 2024-12-10 11:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0003_hotel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Counties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("osm_id", models.CharField(max_length=255)),
                ("name_tag", models.CharField(max_length=255)),
                ("name_ga", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(max_length=255)),
                ("alt_name", models.CharField(blank=True, max_length=255, null=True)),
                ("alt_name_g", models.CharField(blank=True, max_length=255, null=True)),
                ("logainm_re", models.CharField(blank=True, max_length=255, null=True)),
                ("osm_user", models.CharField(blank=True, max_length=255, null=True)),
                ("osm_timest", models.DateTimeField(blank=True, null=True)),
                ("attributio", models.CharField(blank=True, max_length=255, null=True)),
                ("t_ie_url", models.URLField(blank=True, max_length=255, null=True)),
                ("area", models.FloatField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("epoch_tstm", models.IntegerField(blank=True, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ElectoralDistricts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("osm_id", models.CharField(max_length=255)),
                ("name_tag", models.CharField(max_length=255)),
                ("name_ga", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(max_length=255)),
                ("alt_name", models.CharField(blank=True, max_length=255, null=True)),
                ("alt_name_g", models.CharField(blank=True, max_length=255, null=True)),
                ("osm_user", models.CharField(blank=True, max_length=255, null=True)),
                ("osm_timest", models.DateTimeField(blank=True, null=True)),
                ("attributio", models.CharField(blank=True, max_length=255, null=True)),
                ("logainm_re", models.CharField(blank=True, max_length=255, null=True)),
                ("co_name", models.CharField(max_length=255)),
                ("co_osm_id", models.CharField(max_length=255)),
                ("t_ie_url", models.URLField(blank=True, max_length=255, null=True)),
                ("area", models.FloatField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("epoch_tstm", models.IntegerField(blank=True, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
    ]
