# Generated by Django 5.1 on 2025-01-01 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0003_cafe_userprofile_remove_profile_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FavouriteCafe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cafe_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("rating", models.FloatField(blank=True, null=True)),
                ("user_ratings_total", models.IntegerField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "cafe_id")},
            },
        ),
        migrations.DeleteModel(
            name="Cafe",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="favorite_cafes",
            field=models.ManyToManyField(
                related_name="favourited_by", to="world.favouritecafe"
            ),
        ),
    ]
