# Generated by Django 5.1.4 on 2024-12-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_counties_electoraldistricts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electoraldistricts',
            name='osm_id',
            field=models.BigIntegerField(),
        ),
    ]
