# Generated by Django 5.1.4 on 2024-12-10 12:11

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0006_alter_electoraldistricts_co_osm_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electoraldistricts',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
