# Generated by Django 5.1.4 on 2024-12-10 12:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0007_alter_electoraldistricts_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counties',
            name='epoch_tstm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='counties',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
        migrations.AlterField(
            model_name='counties',
            name='osm_id',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='counties',
            name='osm_timest',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
