# Generated by Django 5.1.4 on 2024-12-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0008_alter_counties_epoch_tstm_alter_counties_geom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counties',
            name='name_en',
            field=models.CharField(blank=True, default='Unknown', max_length=255),
        ),
    ]
