# Generated by Django 5.1.4 on 2024-12-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0010_alter_counties_name_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counties',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
