# Generated by Django 5.1.4 on 2024-12-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0011_alter_counties_name_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counties',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='electoraldistricts',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
