# Generated by Django 5.1.4 on 2024-12-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0012_alter_counties_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electoraldistricts',
            name='co_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
